CREATE DATABASE contactsapp;
USE contactsapp;
CREATE TABLE users (
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	FULLNAME VARCHAR(20) NOT NULL,
	PHOTO_PROFILE VARCHAR(20) NOT NULL,
	PRIMARY KEY (USERNAME)
);
CREATE TABLE contacts (
	ID INT(20) NOT NULL AUTO_INCREMENT,
	USER VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PHONE_NUMBER INT(12) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (USER) REFERENCES users (USERNAME)
);
